### ISSUE TITLE
New commit error

### ISSUE THREAD

**Issue by DenisStetsenko** [matteovinci/gulp-hg#1]
Hey!

I'm getting this error over and over when commit is unsuccessful.
Can you let me know what I'm doing wrong or maybe there is a workaround to solve this issue?
Thank you!

```
Error: Command failed: /bin/sh -c hg commit -m "new commit"

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**GULP TASK**

```
gulp.task('hg:commit', function(donecommit) {
  return gulp.src(projectDir, { buffer: false })
    .pipe(hg.commit('new commit'))
    donecommit();
});
```

**Comment by matteovinci** [comment]
Hi @DenisStetsenko,
Are you getting the error only when the commit is unsuccessful?
It would be useful to understand if your task is executed alone or in a sequence of other gulp tasks.

**Comment by DenisStetsenko** [comment]
Hi @matteovinci,

I actually found a workaround. 

```
// Run STATUS command to check if any file was modified
gulp.task('hg:status', function(callback) {
  hg.status({ cwd: projectDir }, function(error, stdout){

    // IF no error and we have changed files - GO AHEAD (add -> commit -> push)
    if (error == null && stdout){

      // Add files first
      hgADD();

      // Commit files
      hgCOMMIT()

      // Commit files
      hgPUSH()

    }

  });

  callback();

});
```

**Comment by matteovinci** [comment]
Hi @DenisStetsenko,
thanks for your reply.
Have you tried to upgrade the library to the latest release (v1.0.5)? Let me know if you still get the issue.

**Comment by DenisStetsenko** [comment]
@matteovinci I actually did. But I also did rewrite my gulp task, so all good now.
I think this issue could be closed.
Thanks for your help!
